import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Learning Next",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav style={{
          background:"teal",
          fontSize:"50px",
          width:"100%",
          display:"flex",
          justifyContent:"center",
          alignItems:"center"
        }}>
          <Link style={{margin:"10px"}} href="/"><button>home</button></Link>
          <Link style={{margin:"10px"}} href="/posts"><button>posts</button></Link>
          <Link style={{margin:"10px"}} href="/articles"><button>article</button></Link>
        </nav>

        {children}
      </body>
    </html>
  );
}
